{
    # 京东
    "com.jingdong.app.mall": ".main.MainActivity",
    # 京东金融
    "com.jd.jrapp": ".WelcomeActivity",
    # ACFun
    "tv.acfundanmaku.video": "tv.acfun.core.view.activity.MainActivity",
    # BiliBili
    "tv.danmaku.bili": ".ui.splash.SplashActivity",
    # 百度地图
    "com.baidu.BaiduMap": "com.baidu.baidumaps.MapsActivity",
    # IT之家
    "com.ruanmei.ithome": ".MainActivity1",
    # 简书
    "com.jianshu.haruki": "com.baiji.jianshu.ui.splash.SplashScreenActivity",
    # 每日优鲜
    "cn.missfresh.application": "cn.missfresh.main.view.MainActivity",
    # 人人视频
    "com.zhongduomei.rrmj.society": ".function.main.activity.MainActivity",
    # 什么值得买
    "com.smzdm.client.android": ".activity.HomeActivity",
    # 腾讯动漫
    "com.qq.ac.android": ".view.activity.SplashActivity",
    # 网易云音乐
    "com.netease.cloudmusic": ".activity.LoadingActivity",
    # 小黑盒
    "com.max.xiaoheihe": ".SplashActivity",
    # 一加社区
    "com.oneplus.bbs": ".ui.activity.WelcomeActivity",
    # 优酷
    "com.youku.phone": ".ActivityWelcome",
    # 爱奇艺
    "com.qiyi.video": "org.qiyi.android.video.MainActivity",
}
